### ISSUE TITLE
Can't run task.json on linux

### ISSUE THREAD

**Issue by 0x1E4** [Southclaws/vscode-pawn#13]
I trying so hard changing anything, and it still not working.
Please tell me how to compile using tasks.json on linux (with pawncc)

**Comment by Southclaws** [comment]
I can't help without any information. Please elaborate on the issue you're running into.

**Comment by 0x1E4** [comment]
Okay..

Here is my detailed information:
Operating System: Manjaro (Arch Linux)
Pawn version: 3.0.19

I trying to change some settings like adding parameter -Z or -d3, and it shows me YSI error, then i change include folder from pawno to my samp03 folder and the error change differently, then i change my direction to ../include and still error.

Do you have any solution for this?

**Comment by Southclaws** [comment]
>  Pawn version: 3.0.19
Do you mean 3.10.9? There is no 3.0.19 that I know of.

> I trying to change some settings like adding parameter -Z or -d3
`-Z+` is necessary with the community compiler, read more here: https://github.com/pawn-lang/compiler/#how-to-use
And `d3` is purely for generating debug code, it will make absolutely no difference to the compile-time invocation, warnings/errors or include directories.

> it shows me YSI error
What error?

You need to show your directory setup and your `tasks.json` file as well as the actual problem you're having, it's still guesswork at this point.

It might be worth first just writing a basic shell script to invoke the compiler with your desired options then convert that into the `tasks.json` format with `command` and `args`.

**Comment by 0x1E4** [comment]
Sorry i forgot to put tasks.json:

`{
    "version": "2.0.0",
    "tasks": [
      {
        "label": "build-normal",
        "type": "shell",
        "command": "pawncc",
        "args": ["\"${relativeFile}\"", "-iinclude", "\"-;+\"", "\"-(+\"", "-Z+"],
        "group": {
          "kind": "build",
          "isDefault": true
        },
        "isBackground": false,
        "presentation": {
          "reveal": "silent",
          "panel": "dedicated"
        },
        "problemMatcher": "$pawncc"
      }
    ]
  }`

**Comment by ADRFranklin** [comment]
Closing this as an old stale issue, please reopen if you are still having this problem
