### ISSUE TITLE
Update Extension on VS marketplace(outdated)

### ISSUE THREAD

**Issue by Zorono** [Southclaws/vscode-pawn#19]
- https://marketplace.visualstudio.com/items?itemName=southclaws.vscode-pawn
![image](https://user-images.githubusercontent.com/19735243/74256623-53d29280-4cfc-11ea-885d-ba143df0726d.png)

**Comment by EOussama** [comment]
I was wondering why the extension had no recent changes, I guess we should have a marketplace update at least once a month.

**Comment by Southclaws** [comment]
Given the frequency of changes, it's not worth it.
