### ISSUE TITLE
Merge with zndn1997/vscode-pawn

### ISSUE THREAD

**Issue by Zorono** [Southclaws/vscode-pawn#24]
what is the possibility of merging with https://github.com/zndn1997/vscode-pawn ?

**Comment by Southclaws** [comment]
Depends entirely what the features of that extension are. I'm not really actively maintaining this aside from accepting pull requests.

**Comment by Zorono** [comment]
> Depends entirely what the features of that extension are. I'm not really actively maintaining this aside from accepting pull requests.

https://github.com/zndn1997/vscode-pawn/blob/master/README.md#specification

my question is generally based on the `Auto Complete`

**Comment by Southclaws** [comment]
Completions are already in: https://github.com/Southclaws/vscode-pawn/blob/master/snippets/functions-community.json
