### ISSUE TITLE
Compiler in OSX

### ISSUE THREAD

**Issue by argololuan** [Southclaws/vscode-pawn#31]
Hello friends!
How do I compile from MAC OSX? I recently purchased the MacBook Air 2019 and I am having immense difficulty compiling.

Already taking advantage of the topic, is there how to run SA-MP on OSX?

**Comment by argololuan** [comment]
Hi,

Are there any tutorials teaching how to use Docker?

**Comment by Southclaws** [comment]
There are thousands online, it's one of the most popular development and deployment tools currently.

At the bare minimum, `docker run -it ubuntu` would get you into an ununtu shell ready to run sampctl.
