### ISSUE TITLE
Syntax colouring issue

### ISSUE THREAD

**Issue by ltkarim** [Southclaws/vscode-pawn#4]
Hey,

I have been using this for quite sometime now, though I have a problem with this specific syntax I use for my script:

```pawn
MODULE::Test
```

Unlike the colouring above, it colours `MODULE:` as if it was a tag and `:Test` is white, which is quite annoying, is there any way to fix that?

**Comment by Southclaws** [comment]
That's not standard Pawn syntax, `MODULE:` is a tag as far as the parser and the language is concerned. If this is a preprocessor macro, the syntax engine has no knowledge of these macros and cannot adjust the syntax for these cases.
